package security

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
	
	/**
	 * Array of controller/action combinations which will be skipped from authentication
	 * if the controller and action names match. The action value can also be '*' if it
	 * encompasses all actions within the controller.
	 */
//	static nonAuthenticatedActions = [
//			//[controller: 'auth', action: '*']
//	]

	/**
	 * Array of controller/action combinations that will be authenticated against the user's
	 * role. The map also includes the roles which the controller/action pair will match
	 * against.
	 */
//	static authenticatedActions = [
////			[controller: 'home', action: 'secured', roles: ['ROLE_ADMIN', 'ROLE_USER']],
////			[controller: 'home', action: 'admin', roles: ['ROLE_ADMIN']]
//	]
	
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
//				if (!controllerName || controllerName=='home' || (controllerName=='main' && SecurityUtils.subject.principal!=null))
//					return true
				
				if (!controllerName) return true
                // Access control by convention.
                accessControl()
            }
        }
    }
	
}
